### ISSUE TITLE
Add 'final' modules

### ISSUE THREAD

**Issue by awoods** [duraspace/codestyle#5]
The "FinalLocalVariable" and "FinalParameters" modules should be added to the [TreeWalker](https://github.com/duraspace/codestyle/blob/master/duraspace-checkstyle.xml#L41) module.
See: https://github.com/fcrepo4/fcrepo-build-tools/blob/master/src/main/resources/fcrepo-checkstyle/checkstyle.xml#L86-L87

Note, for ease of testing this change, https://github.com/duraspace/codestyle/issues/4 should be completed first.

**Comment by bbranan** [comment]
More information on why these modules should be added would be helpful in understanding their purpose and the benefit of including them.

**Comment by awoods** [comment]
@bbranan : see: https://github.com/duraspace/codestyle/pull/7/files#diff-6b740b6fa3b1c3054017c2b0e2f8ed0cR61
